force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>STU-{0000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Student first Name</description>
    <label>First Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/State_Of_Origin__c.field-meta.xml
<CustomField>
    <fullName>State_Of_Origin__c</fullName>
    <label>State Of Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abia</fullName>
            </value>
            <value>
                <fullName>Adamawa</fullName>
            </value>
            <value>
                <fullName>Akwa Ibom</fullName>
            </value>
            <value>
                <fullName>Anambra</fullName>
            </value>
            <value>
                <fullName>Bauchi</fullName>
            </value>
            <value>
                <fullName>Bayelsa</fullName>
            </value>
            <value>
                <fullName>Benue</fullName>
            </value>
            <value>
                <fullName>Borno</fullName>
            </value>
            <value>
                <fullName>Cross River</fullName>
            </value>
            <value>
                <fullName>Delta</fullName>
            </value>
            <value>
                <fullName>Ebonyi</fullName>
            </value>
            <value>
                <fullName>Edo</fullName>
            </value>
            <value>
                <fullName>Ekiti</fullName>
            </value>
            <value>
                <fullName>Enugu</fullName>
            </value>
            <value>
                <fullName>FCT</fullName>
            </value>
            <value>
                <fullName>Gombe</fullName>
            </value>
            <value>
                <fullName>Imo</fullName>
            </value>
            <value>
                <fullName>Jigawa</fullName>
            </value>
            <value>
                <fullName>Kaduna</fullName>
            </value>
            <value>
                <fullName>Kano</fullName>
            </value>
            <value>
                <fullName>Katsina</fullName>
            </value>
            <value>
                <fullName>Kebbi</fullName>
            </value>
            <value>
                <fullName>Kogi</fullName>
            </value>
            <value>
                <fullName>Kwara</fullName>
            </value>
            <value>
                <fullName>Lagos</fullName>
            </value>
            <value>
                <fullName>Nassarawa</fullName>
            </value>
            <value>
                <fullName>Niger</fullName>
            </value>
            <value>
                <fullName>Ogun</fullName>
            </value>
            <value>
                <fullName>Ondo</fullName>
            </value>
            <value>
                <fullName>Osun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentRestService.cls
@RestResource(urlmapping='/students')
public class StudentRestService {



    /**
     * @description GetStudents checks the url to confirm that there is a series of Id
     * for every ID specified in the request body , it returns valid records!!!
     * @return   return description
     */ 
    @HttpGet
    public static List<Student__c> GetAllStudentsOrGetStudentsById(){  
        RestRequest req = RestContext.Request;

        string query = 'Select Id, First_Name__c, Last_Name__c , Gender__c,State_Of_Origin__c From Student__c';
        if(req.requestBody != null) {
            List<string> studentIds = Json.deserialize(req.requestBody.toString(), List<String>.class);
            query += 'Where Id IN :studentIds';
        }
        return (List<Student__c>)Database.execute(query);
    }


    @HttpPost
    public  static void UpdateStudentRecord(UpdateStudentModel reqBody){
        RestResponse res = RestContext.response;
        if(reqBody != null){
            List<Student__c> queryRes = [Select First_Name__c, Last_Name__c , Gender__c , State_Of_Origin__c , Class__c from Student where Id =: reqBody.Id];
            
            if(queryRes != null && queryRes.size() > 0){
                Student__c foundRecord = queryRes[0];
                foundRecord.First_Name__c = String.isBlank(reqBody.firstName) || reqBody.firstName == null ? foundRecord.First_Name__c : reqBody.firstName;
                foundRecord.Last_Name__c = String.isBlank(reqBody.lastName) || reqBody.lastName == null ? foundRecord.Last_Name__c : reqBody.lastName;
                foundRecord.Gender__c = String.isBlank(reqBody.gender) || reqBody.gender == null ? foundRecord.Gender__c : reqBody.gender;
                foundRecord.State_Of_Origin__c = String.isBlank(reqBody.state) || reqBody.state == null ? foundRecord.State_Of_Origin__c : reqBody.state;
                foundRecord.Class__c = String.isBlank(reqBody.studentClass) || reqBody.studentClass == null ? foundRecord.Class__c : reqBody.studentClass;
                
                try{
                    update queryRes;
                    res.statusCode = 200;
                    res.responseBody = Blob.valueOf('Record updated successfully');
                
                }catch(Exception e){
                    res.statusCode = 500;
                    res.responseBody = Blob.valueOf('An Error Has occured While trying to update the record: ' + e.getMessage());
                }
                
            
            }

        }

    }



    @HttpDelete
    public static void DeleteRecords(){
        RestRequest req = RestContext.Request;
        RestResponse res = RestContext.Response;
        string query = 'Select Id, First_Name__c, Last_Name__c , Gender__c,State_Of_Origin__c From Student__c';
        if(req.requestBody != null) {
            List<string> studentIds = Json.deserialize(req.requestBody.toString(), List<String>.class);
            query += 'Where Id IN :studentIds';
            List<Student__c> response = (List<Student__c>)Database.execute(query);
            delete response;
            res.statusCode = 204;
            res.responseBody = Blob.valueOf('Records Deleted Successfully');
        }
    }
    
}